[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_1"
path = "src/day_1.rs"

[[bin]]
name = "day_2"
path = "src/day_2.rs"

[[bin]]
name = "day_3"
path = "src/day_3.rs"

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"
